module Marijuanacoin
  PERFORM_ERROR = 'Sorry, I do not know that command. Type `DabBot commands` to learn more about me.'
  BALANCE_REPLY_PRETEXT = 'your balance is:'
  CURRENCY_ICON = 'MAR'
  WEALTHY_UPPER_BOUND = 1000
  WEALTHY_UPPER_BOUND_POSTTEXT = ' '
  WEALTHY_UPPER_BOUND_EMOJI = ':moneybag:'
  BALANCE_REPLY_POSTTEXT = ' '
  DEPOSIT_PRETEXT = 'Send your coins to'
  DEPOSIT_POSTTEXT = ', this is your personal Marijuanacoin address!'
  TIP_ERROR_TEXT = 'Please say `DabBot tip @username amount` or `DabBot help` for more info.'
  TIP_PRETEXT = 'I am sending a tip from'
  TIP_POSTTEXT1 = 'http://explorer.marijuanacoin.dabsolutions.co/tx/'
  TIP_POSTTEXT2 = '|Block Explorer'
  WITHDRAW_TEXT = 'A withdraw by'
  WITHDRAW_ICON = ''
  NETWORKINFO_ICON = ':bar_chart:'
  TOO_POOR_TEXT = 'Not enough coins. Sorry.'
  NO_PURPOSE_LOWER_BOUND_TEXT = 'Too small. Withdraws above 0.0001 only.'
  NO_PURPOSE_LOWER_BOUND = 0.0001
  RANDOMIZED_EMOJI = ' '
  TIPPING_EMOJI = ':money_with_wings:'
  GITHUB_EMOJI = ':github:'
  MARIJUANA_EMOJI = ':desktop_computer:'
  NETWORK = 'marijuanacoin'
  TADA_EMOJI = ':tada:'
end
